PublicKey:  ""
Customer: "test"
StartPort:  8081
Proxychains: "/usr/local/etc/proxychains.conf"
CobaltStrikeDir: "/tmp/cobaltstrike"
CobaltStrikeProfiles: ""
CobaltStrikeLicense: ""
NmapDir: "/tmp/cloudNmaps"
LogDir: "/tmp/hideNsneak/"
AWS:
    secret: ""
    accessID: ""
    regions: "us-east-1,us-east-2,us-west-1,us-west-2"
    imageIDs: "ami-66506c1c,ami-965e6bf3,ami-07585467,ami-79873901"
    type: "t2.micro"
    username: "ubuntu"
DO:
    token: ""
    fingerprint: ""
    regions: "*"
    slug: "ubuntu-14-04-x64"
    memory: "512mb"
    name: "clientName"
    username: "root"
Google:
    imageProject: "ubuntu-1604-xenial"
    machineType: "f1-micro"
    zones: "us-central1-f"
    project: ""
    name: "googleTest"
    username: ""
